# This is a basic workflow to help you get started with Actions

name: Crear Dist

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Use Node.js 14.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Instalacion de dependencias
        run: npm install

      - name: construccion de dist
        run: npm run build

      - name: agregar nevo dist a gh-pages
        run: |
          git config user.name maoSantaella
          git config user.email mao.santaella@gmail.com
          git checkout -b newdist
          git add --force dist
          git commit -m "new dist"
          git push -u origin newdist
          git push origin `git subtree split --prefix dist newdist`:gh-pages --force
          git push origin --delete newdist

# git subtree push --prefix dist origin gh-pages
